gcp_project_id = "gcp_project_id_12345"
region =  "us-central1"
zone = "us-central1-c"
vm_name = "tf-gcp-vm"
vm_type = "n1-standard-1"
vm_image = "centos-cloud/centos-7"
vm_image_type = "pd-standard"
source_account_email = "1234567-compute@developer.gserviceaccount.com"
