gcp_project_id = "tensile-tenure-225805"
region =  "us-central1"
zone = "us-central1-c"
vm_name = "tf-gcp-vm"
vm_type = "n1-standard-1"
vm_image = "centos-cloud/centos-7"
vm_image_type = "pd-standard"
source_account_email = "gcp-vm-auth@tensile-tenure-225805.iam.gserviceaccount.com"
