name: Terraform GCP Validate

on:
  push:
    branches: [ main ]
    paths:
      - 'gcp/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'gcp/**'
  workflow_dispatch:
    inputs:
      tfpath:
        description: 'TF Code Path'
        required: false
        default: 'gcp/resources'

jobs:
  terraform_validate:
    name: Terraform Validate – GCP
    runs-on: ubuntu-latest
    env:
      TFPATH: ${{ github.event.inputs.tfpath || 'gcp/resources' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.2

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2.0.2

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: ${{ env.TFPATH }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TFPATH }}
